[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", exclude = "\\.snap$" },
  { id = "end-of-file-fixer", exclude = "\\.snap$" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "check-added-large-files" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-build"
name = "cargo build"
entry = "cargo build --workspace"
language = "system"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-test"
name = "cargo test"
entry = "cargo test --workspace"
language = "system"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
entry = "bash -c 'cargo fmt -- \"$@\" && git add \"$@\"' --"
language = "system"
pass_filenames = true
types = ["rust"]
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
entry = "cargo clippy --workspace --all-targets"
language = "system"
pass_filenames = false
always_run = true
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-test-integration"
name = "cargo test (integration)"
entry = "cargo test --workspace --features integration"
language = "system"
pass_filenames = false
always_run = true
stages = ["pre-push"]
