background = "#282A36"
border_unfocused_fg = "#6272A4"
primary_accent_fg = "#BD93F9"
secondary_accent_fg = "#8BE9FD"
source_selector_producer_fg = "#BD93F9"
source_selector_group_fg = "#FFB86C"
source_selector_source_fg = "#F8F8F2"
log_selected_bg = "#44475A"
log_selected_modifier = "BOLD"
log_match_fg = "#F1FA8C"
log_match_style = "color"
log_match_bold = true
status_dim = true

[log_level]
default_fg = "#F8F8F2"
trace_fg = "#6272A4"
debug_fg = "#8BE9FD"
info_fg = "#50FA7B"
warn_fg = "#F1FA8C"
error_fg = "#FF5555"
fatal_fg = "#FF79C6"
