background = "#181616"
border_unfocused_fg = "Reset"
primary_accent_fg = "#C4B28A"
query_prompt_fg = "#87A987"
log_selected_bg = "#2D4F67"
log_match_fg = "#8BA4B0"
log_match_bold = true
status_dim = true

[log_level]
default_fg = "#C5C9C5"
trace_fg = "#625E5A"
debug_fg = "#625E5A"
info_fg = "#87A987"
warn_fg = "#C4B28A"
error_fg = "#C4746E"
fatal_fg = "#A292A3"
