background = "#181616"
border_unfocused_fg = "#54546D"
primary_accent_fg = "#C4B28A"
secondary_accent_fg = "#87A987"
source_selector_producer_fg = "#C4B28A"
source_selector_group_fg = "#87A987"
source_selector_source_fg = "#C5C9C5"
log_selected_bg = "#2D4F67"
log_selected_modifier = "BOLD"
log_match_fg = "#8BA4B0"
log_match_style = "color"
log_match_bold = true
status_dim = true

[log_level]
default_fg = "#C5C9C5"
trace_fg = "#6E6660"
debug_fg = "#8BA4B0"
info_fg = "#87A987"
warn_fg = "#C4B28A"
error_fg = "#C4746E"
fatal_fg = "#A292A3"
