background = "#1A1B26"
border_unfocused_fg = "#565F89"
primary_accent_fg = "#7AA2F7"
secondary_accent_fg = "#BB9AF7"
source_selector_producer_fg = "#7AA2F7"
source_selector_group_fg = "#73DACA"
source_selector_source_fg = "#C0CAF5"
log_selected_bg = "#292E42"
log_selected_modifier = "BOLD"
log_match_fg = "#E0AF68"
log_match_style = "color"
log_match_bold = true
status_dim = true

[log_level]
default_fg = "#C0CAF5"
trace_fg = "#565F89"
debug_fg = "#7DCFFF"
info_fg = "#9ECE6A"
warn_fg = "#E0AF68"
error_fg = "#F7768E"
fatal_fg = "#FF9E64"
