[package]
name = "fml"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
clap.workspace = true
crossterm.workspace = true
ratatui.workspace = true
ratatui-textarea.workspace = true
tui-scrollview.workspace = true
tui-popup.workspace = true
tokio.workspace = true
bytes.workspace = true
notify.workspace = true
regex.workspace = true
bollard.workspace = true
futures-util.workspace = true
kube.workspace = true
k8s-openapi.workspace = true
anyhow.workspace = true
color-eyre.workspace = true
lazy_static.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-error.workspace = true
tracing-appender.workspace = true
thiserror.workspace = true
chrono.workspace = true
serde_json.workspace = true
fake.workspace = true
rand.workspace = true
config.workspace = true
serde.workspace = true
frizbee.workspace = true


[features]
integration = []

[dev-dependencies]
insta.workspace = true
serial_test = "3.4.0"
tempfile = "3.27.0"

[build-dependencies]
anyhow.workspace = true
vergen-gix = { version = "9.1.0", features = ["build", "cargo"] }
